export const Abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'user',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'uint256',
                name: 'nftId',
                type: 'uint256',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'nftAddress',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'launchIndex',
                type: 'uint256',
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'historyIndex',
                type: 'uint256',
            },
        ],
        name: 'Buy',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: 'uint8',
                name: 'version',
                type: 'uint8',
            },
        ],
        name: 'Initialized',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'bytes32',
                name: 'role',
                type: 'bytes32',
            },
            {
                indexed: true,
                internalType: 'bytes32',
                name: 'previousAdminRole',
                type: 'bytes32',
            },
            {
                indexed: true,
                internalType: 'bytes32',
                name: 'newAdminRole',
                type: 'bytes32',
            },
        ],
        name: 'RoleAdminChanged',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'bytes32',
                name: 'role',
                type: 'bytes32',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'account',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'sender',
                type: 'address',
            },
        ],
        name: 'RoleGranted',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'bytes32',
                name: 'role',
                type: 'bytes32',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'account',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'sender',
                type: 'address',
            },
        ],
        name: 'RoleRevoked',
        type: 'event',
    },
    {
        inputs: [],
        name: 'ADMIN_ACTION_ROLE',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'DEFAULT_ADMIN_ROLE',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint32', name: '_totalCount', type: 'uint32' },
            {
                internalType: 'address',
                name: '_erc20TokenAddress',
                type: 'address',
            },
            {
                internalType: 'uint256',
                name: '_erc20TokenAmount',
                type: 'uint256',
            },
            {
                internalType: 'address',
                name: '_loyaltyAddress',
                type: 'address',
            },
            { internalType: 'address', name: '_nftAddress', type: 'address' },
            { internalType: 'uint32', name: '_loyaltyFees', type: 'uint32' },
            { internalType: 'string', name: '_carType', type: 'string' },
            { internalType: 'string', name: '_carModel', type: 'string' },
        ],
        name: 'addNewLaunch',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_launchIndex', type: 'uint256' },
        ],
        name: 'buyNFT',
        outputs: [{ internalType: 'uint256', name: 'nftId', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getLaunchpadLength',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
        name: 'getRoleAdmin',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'grantRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'hasRole',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'histories',
        outputs: [
            { internalType: 'uint256', name: 'nftId', type: 'uint256' },
            { internalType: 'address', name: 'nftAddress', type: 'address' },
            {
                internalType: 'address',
                name: 'erc20TokenAddress',
                type: 'address',
            },
            {
                internalType: 'uint256',
                name: 'erc20TokenAmount',
                type: 'uint256',
            },
            { internalType: 'address', name: 'user', type: 'address' },
            {
                internalType: 'uint256',
                name: 'createTimestamp',
                type: 'uint256',
            },
            { internalType: 'uint256', name: 'launchIndex', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'historyLength',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_treasuryAddress',
                type: 'address',
            },
        ],
        name: 'initialize',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'launches',
        outputs: [
            {
                internalType: 'address',
                name: 'erc20TokenAddress',
                type: 'address',
            },
            {
                internalType: 'uint256',
                name: 'erc20TokenAmount',
                type: 'uint256',
            },
            { internalType: 'string', name: 'carType', type: 'string' },
            { internalType: 'string', name: 'carModel', type: 'string' },
            { internalType: 'address', name: 'carAddress', type: 'address' },
            { internalType: 'uint32', name: 'totalCount', type: 'uint32' },
            { internalType: 'uint32', name: 'soldCount', type: 'uint32' },
            {
                internalType: 'address payable',
                name: 'loyaltyAddress',
                type: 'address',
            },
            { internalType: 'uint32', name: 'loyaltyFees', type: 'uint32' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_index', type: 'uint256' }],
        name: 'launchpadLeftToSell',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'paused',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'renounceRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'revokeRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            {
                internalType: 'address payable',
                name: '_treasuryAddress',
                type: 'address',
            },
        ],
        name: 'setTreasuryAddress',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' },
        ],
        name: 'supportsInterface',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'treasuryAddress',
        outputs: [
            { internalType: 'address payable', name: '', type: 'address' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'unpause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint32', name: '_index', type: 'uint32' },
            { internalType: 'uint32', name: '_totalCount', type: 'uint32' },
            { internalType: 'uint256', name: '_erc20Amount', type: 'uint256' },
            { internalType: 'address', name: '_erc20Address', type: 'address' },
            {
                internalType: 'address',
                name: '_loyaltyAddress',
                type: 'address',
            },
            { internalType: 'uint32', name: '_loyaltyFees', type: 'uint32' },
        ],
        name: 'updateLaunch',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
];
