export enum ENUM_PRODUCT_STATUS_CODE_ERROR {
    PRODUCT_NOT_FOUND_ERROR = 5700,
    PRODUCT_EXISTS_ERROR = 5701,
    
}

export enum ENUM_PRODUCT_STATUS_CODE_SUCCESS {
    PRODUCT_LOGIN_SUCCESS = 1001,
}
